folder_in: /home/user2/tst/file
folder_out: /home/user2/tst/out
folder_ext: /home/user2/tst/ext
folder_badarx: /home/user2/tst/badarx


archive_type: 7z
count_file: 2
size_file: 5M

local_path: /home/linux
remote_path: /home/user2
host: 0.0.0.0
user: user2

stat_file: /home/user2/stat.txt